export const ROUTES = {
  HOME: '/',
  COURSES: '/app/courses',
  APP: '/app/courses/my',
  ALL_COURSES: '/app/courses/all',
  CREATED_COURSES: '/app/courses/created',
  PROFILE: '/app/profile/my',
  HELP: '/app/help',
  RESET: '/auth/reset',
  SIGN_UP: '/auth/sign-up',
  SIGN_IN: '/auth/sign-in',
  DASHBOARD: '/app/dashboard',
  EDIT_COURSE: '/app/courses/edit',
  BUY: '/app/buy',
};
