import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';
import './globals.css';
import styles from './page.module.css';
import LeftMenu from './components/left-menu/left-menu';

const notoSans = Noto_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'PushToLearn',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={notoSans.className}>
        <div className={styles.wrapper}>
          <div className={styles.header}>Header</div>
          <LeftMenu></LeftMenu>
          <main className={styles.main}>
            <div className={styles.innerContainer}>{children}</div>
          </main>
        </div>
      </body>
    </html>
  );
}
