import Image from 'next/image';
import styles from './page.module.css';
import { Metadata } from 'next';
import { Button, Htag, P, Tag } from '@/app/(site)/components';

// export const metadata: Metadata = {
//   title: 'Курсы',
//   description: 'Generated by create next app',
// };

export async function generateMetadata(): Promise<Metadata> {
  return {
    title: 'Главная страница',
  };
}

export default function Home() {
  return (
    <main className={styles.main}>
      <div className={styles.innerContainer}>
        <Htag tag="h1">Текст</Htag>
        <Button appearance="ghost">Начать</Button>
        <Button appearance="primary" count={6}>
          Начать
        </Button>
        <Button appearance="ghost" count={10}>
          Начать
        </Button>
        <Tag>Frontend</Tag>
        <P size="small">Текст</P>
      </div>
    </main>
  );
}
