/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * server
 * OpenAPI spec version: 1.0.0
 */
import { createInstance } from './api-instance';
import type { BodyType } from './api-instance';
export type LessonDtoType = (typeof LessonDtoType)[keyof typeof LessonDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LessonDtoType = {
  Theory: 'Theory',
  Test: 'Test',
  Exercise: 'Exercise',
} as const;

export type LessonDtoData = { [key: string]: any };

export interface LessonDto {
  createdAt: string;
  data: LessonDtoData;
  id: number;
  sectionId: number;
  sequence: number;
  title: string;
  type: LessonDtoType;
  updatedAt: string;
}

export type PatchLessonDtoData = { [key: string]: any };

export interface PatchLessonDto {
  data: PatchLessonDtoData;
  sequence: number;
  title: string;
}

export type CreateLessonDtoType =
  (typeof CreateLessonDtoType)[keyof typeof CreateLessonDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateLessonDtoType = {
  Theory: 'Theory',
  Test: 'Test',
  Exercise: 'Exercise',
} as const;

export type CreateLessonDtoData = { [key: string]: any };

export interface CreateLessonDto {
  data: CreateLessonDtoData;
  sectionId: number;
  title: string;
  type: CreateLessonDtoType;
}

export interface SectionDto {
  courseId: number;
  createdAt: string;
  id: number;
  sequence: number;
  title: string;
  updatedAt: string;
}

export interface PatchSectionDto {
  sequence: number;
  title: string;
}

export interface CreateSectionDto {
  courseId: number;
  title: string;
}

export type LessonDtoWithViewedType =
  (typeof LessonDtoWithViewedType)[keyof typeof LessonDtoWithViewedType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LessonDtoWithViewedType = {
  Theory: 'Theory',
  Test: 'Test',
  Exercise: 'Exercise',
} as const;

export type LessonDtoWithViewedData = { [key: string]: any };

export interface LessonDtoWithViewed {
  createdAt: string;
  data: LessonDtoWithViewedData;
  id: number;
  sectionId: number;
  sequence: number;
  title: string;
  type: LessonDtoWithViewedType;
  updatedAt: string;
  viewed: boolean;
}

export interface CourseDtoWithSections {
  author: string;
  createdAt: string;
  duration: string;
  historyLessonId: number;
  historySectionId: number;
  id: number;
  img: string;
  lessonCompleted: number;
  lessonCount: number;
  price: number;
  sectionsWithLessonsStat: SectionsWithLessonsStatDto[];
  sequence: number;
  tags: string[];
  title: string;
  updatedAt: string;
}

export type LessonStatType =
  (typeof LessonStatType)[keyof typeof LessonStatType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LessonStatType = {
  Theory: 'Theory',
  Test: 'Test',
  Exercise: 'Exercise',
} as const;

export interface LessonStat {
  id: number;
  sequence: number;
  title: string;
  type: LessonStatType;
  viewed: boolean;
}

export interface SectionsWithLessonsStatDto {
  courseId: number;
  createdAt: string;
  id: number;
  lessonsStat: LessonStat[];
  sequence: number;
  title: string;
  updatedAt: string;
}

export interface CourseDtoWithUserStat {
  author: string;
  createdAt: string;
  duration: string;
  historyLessonId: number;
  historySectionId: number;
  id: number;
  img: string;
  lessonCompleted: number;
  lessonCount: number;
  price: number;
  sequence: number;
  tags: string[];
  title: string;
  updatedAt: string;
}

export interface CourseDtoWithLessonCount {
  author: string;
  createdAt: string;
  duration: string;
  id: number;
  img: string;
  lessonCount: number;
  price: number;
  sequence: number;
  tags: string[];
  title: string;
  updatedAt: string;
}

export interface CourseDto {
  author: string;
  createdAt: string;
  duration: string;
  id: number;
  img: string;
  price: number;
  sequence: number;
  tags: string[];
  title: string;
  updatedAt: string;
}

export interface PatchCourseDto {
  duration: string;
  img: string;
  price: number;
  sequence: number;
  tags: string[];
  title: string;
}

export interface CreateCourseDto {
  duration: string;
  img: string;
  price: number;
  tags: string[];
  title: string;
}

export interface PatchAccountDto {
  firstName: string;
  lastName: string;
  username: string;
}

export interface AccountDto {
  firstName: string;
  id: number;
  lastName: string;
  userId: number;
  username: string;
}

export interface SessionInfoDto {
  email: string;
  exp: number;
  iat: number;
  id: number;
  role: string;
}

export interface SignInBodyDto {
  email: string;
  password: string;
}

export interface PatchUpdateRoleDto {
  email: string;
  role: string;
}

export interface SignUpBodyDto {
  email: string;
  firstName: string;
  lastName: string;
  password: string;
}

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

export const authControllerSignUp = (
  signUpBodyDto: BodyType<SignUpBodyDto>,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<void>(
    {
      url: `/auth/sign-up`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: signUpBodyDto,
    },
    options,
  );
};

export const authControllerUpdateRole = (
  patchUpdateRoleDto: BodyType<PatchUpdateRoleDto>,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<void>(
    {
      url: `/auth/update`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: patchUpdateRoleDto,
    },
    options,
  );
};

export const authControllerDelete = (
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<string>(
    { url: `/auth/delete`, method: 'DELETE' },
    options,
  );
};

export const authControllerSignIn = (
  signInBodyDto: BodyType<SignInBodyDto>,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<void>(
    {
      url: `/auth/sign-in`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: signInBodyDto,
    },
    options,
  );
};

export const authControllerSignOut = (
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<void>(
    { url: `/auth/sign-out`, method: 'POST' },
    options,
  );
};

export const authControllerGetSessionInfo = (
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<SessionInfoDto>(
    { url: `/auth/session`, method: 'GET' },
    options,
  );
};

export const accountControllerGetAccount = (
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<AccountDto>(
    { url: `/account`, method: 'GET' },
    options,
  );
};

export const accountControllerPatchAccount = (
  patchAccountDto: BodyType<PatchAccountDto>,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<AccountDto>(
    {
      url: `/account`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: patchAccountDto,
    },
    options,
  );
};

export const coursesControllerCreate = (
  createCourseDto: BodyType<CreateCourseDto>,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<void>(
    {
      url: `/courses/create`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createCourseDto,
    },
    options,
  );
};

export const coursesControllerPatchCourse = (
  courseId: number,
  patchCourseDto: BodyType<PatchCourseDto>,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<CreateCourseDto>(
    {
      url: `/courses/update/${courseId}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: patchCourseDto,
    },
    options,
  );
};

export const coursesControllerGetAllCourses = (
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<CourseDto[]>(
    { url: `/courses`, method: 'GET' },
    options,
  );
};

export const coursesControllerDelete = (
  courseId: number,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<CourseDto>(
    { url: `/courses/${courseId}`, method: 'DELETE' },
    options,
  );
};

export const coursesControllerGetNotMyCourseById = (
  courseId: number,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<CourseDtoWithLessonCount>(
    { url: `/courses/notMy/${courseId}`, method: 'GET' },
    options,
  );
};

export const coursesControllerGetMyCourses = (
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<CourseDtoWithUserStat[]>(
    { url: `/courses/my`, method: 'GET' },
    options,
  );
};

export const coursesControllerGetCourseById = (
  courseId: number,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<CourseDtoWithSections>(
    { url: `/courses/my/${courseId}`, method: 'GET' },
    options,
  );
};

export const coursesControllerGetPageLesson = (
  courseId: number,
  sectionId: number,
  lessonId: number,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<LessonDtoWithViewed>(
    {
      url: `/courses/my/${courseId}/sections/${sectionId}/lessons/${lessonId}`,
      method: 'GET',
    },
    options,
  );
};

export const coursesControllerLessonViewed = (
  courseId: number,
  sectionId: number,
  lessonId: number,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<boolean>(
    {
      url: `/courses/my/${courseId}/sections/${sectionId}/lessons/${lessonId}/viewed`,
      method: 'PATCH',
    },
    options,
  );
};

export const sectionsControllerCreate = (
  createSectionDto: BodyType<CreateSectionDto>,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<void>(
    {
      url: `/sections/create`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createSectionDto,
    },
    options,
  );
};

export const sectionsControllerPatchSection = (
  sectionId: number,
  patchSectionDto: BodyType<PatchSectionDto>,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<SectionDto>(
    {
      url: `/sections/update/${sectionId}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: patchSectionDto,
    },
    options,
  );
};

export const sectionsControllerDeleteSection = (
  sectionId: number,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<void>(
    { url: `/sections/delete/${sectionId}`, method: 'DELETE' },
    options,
  );
};

export const lessonsControllerCreate = (
  createLessonDto: BodyType<CreateLessonDto>,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<void>(
    {
      url: `/lessons/create`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createLessonDto,
    },
    options,
  );
};

export const lessonsControllerPatchCourse = (
  lessonId: number,
  patchLessonDto: BodyType<PatchLessonDto>,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<LessonDto>(
    {
      url: `/lessons/update/${lessonId}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: patchLessonDto,
    },
    options,
  );
};

export const lessonsControllerDeletelesson = (
  lessonId: number,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<void>(
    { url: `/lessons/delete/${lessonId}`, method: 'DELETE' },
    options,
  );
};

export const buyControllerBuyCourse = (
  courseId: number,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<void>(
    { url: `/buy/${courseId}`, method: 'POST' },
    options,
  );
};

export type AuthControllerSignUpResult = NonNullable<
  Awaited<ReturnType<typeof authControllerSignUp>>
>;
export type AuthControllerUpdateRoleResult = NonNullable<
  Awaited<ReturnType<typeof authControllerUpdateRole>>
>;
export type AuthControllerDeleteResult = NonNullable<
  Awaited<ReturnType<typeof authControllerDelete>>
>;
export type AuthControllerSignInResult = NonNullable<
  Awaited<ReturnType<typeof authControllerSignIn>>
>;
export type AuthControllerSignOutResult = NonNullable<
  Awaited<ReturnType<typeof authControllerSignOut>>
>;
export type AuthControllerGetSessionInfoResult = NonNullable<
  Awaited<ReturnType<typeof authControllerGetSessionInfo>>
>;
export type AccountControllerGetAccountResult = NonNullable<
  Awaited<ReturnType<typeof accountControllerGetAccount>>
>;
export type AccountControllerPatchAccountResult = NonNullable<
  Awaited<ReturnType<typeof accountControllerPatchAccount>>
>;
export type CoursesControllerCreateResult = NonNullable<
  Awaited<ReturnType<typeof coursesControllerCreate>>
>;
export type CoursesControllerPatchCourseResult = NonNullable<
  Awaited<ReturnType<typeof coursesControllerPatchCourse>>
>;
export type CoursesControllerGetAllCoursesResult = NonNullable<
  Awaited<ReturnType<typeof coursesControllerGetAllCourses>>
>;
export type CoursesControllerDeleteResult = NonNullable<
  Awaited<ReturnType<typeof coursesControllerDelete>>
>;
export type CoursesControllerGetNotMyCourseByIdResult = NonNullable<
  Awaited<ReturnType<typeof coursesControllerGetNotMyCourseById>>
>;
export type CoursesControllerGetMyCoursesResult = NonNullable<
  Awaited<ReturnType<typeof coursesControllerGetMyCourses>>
>;
export type CoursesControllerGetCourseByIdResult = NonNullable<
  Awaited<ReturnType<typeof coursesControllerGetCourseById>>
>;
export type CoursesControllerGetPageLessonResult = NonNullable<
  Awaited<ReturnType<typeof coursesControllerGetPageLesson>>
>;
export type CoursesControllerLessonViewedResult = NonNullable<
  Awaited<ReturnType<typeof coursesControllerLessonViewed>>
>;
export type SectionsControllerCreateResult = NonNullable<
  Awaited<ReturnType<typeof sectionsControllerCreate>>
>;
export type SectionsControllerPatchSectionResult = NonNullable<
  Awaited<ReturnType<typeof sectionsControllerPatchSection>>
>;
export type SectionsControllerDeleteSectionResult = NonNullable<
  Awaited<ReturnType<typeof sectionsControllerDeleteSection>>
>;
export type LessonsControllerCreateResult = NonNullable<
  Awaited<ReturnType<typeof lessonsControllerCreate>>
>;
export type LessonsControllerPatchCourseResult = NonNullable<
  Awaited<ReturnType<typeof lessonsControllerPatchCourse>>
>;
export type LessonsControllerDeletelessonResult = NonNullable<
  Awaited<ReturnType<typeof lessonsControllerDeletelesson>>
>;
export type BuyControllerBuyCourseResult = NonNullable<
  Awaited<ReturnType<typeof buyControllerBuyCourse>>
>;
